---
abstract: 'Displays better stack trace when your app dies'
author:
  - 'Charlie Somerville'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.2.0, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-BetterStackTrace
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Plack::Middleware::BetterStackTrace:
    file: lib/Plack/Middleware/BetterStackTrace.pm
    version: 0.01
requires:
  Devel::StackTrace::WithLexicals: 0.10
  JSON: 2.57
  Plack: 1.0023
  Term::ANSIColor: 4.00
  Text::Xslate: 2.00
  perl: 5.008005
resources:
  bugtracker: https://github.com/gunyarakun/Plack-Middleware-BetterStackTrace/issues
  homepage: https://github.com/gunyarakun/Plack-Middleware-BetterStackTrace
  repository: git://github.com/gunyarakun/Plack-Middleware-BetterStackTrace.git
version: 0.01
x_contributors:
  - 'Tasuku SUENAGA a.k.a. gunyarakun <tasuku-s-github@titech.ac>'
